const FromInfo: Array<{
  label: string;
  name: string;
  options: Array<{
    label: string;
    value: string;
  }>;
}> = [
  {
    label: '按地区',
    name: 'area',
    options: [
      {
        label: '全部',
        value: '',
      },
      {
        label: '日本',
        value: 'japan',
      },
      {
        label: '港台',
        value: 'hongkong',
      },
      {
        label: '其他',
        value: 'other',
      },
      {
        label: '欧美',
        value: 'europe',
      },
      {
        label: '大陆',
        value: 'china',
      },
      {
        label: '韩国',
        value: 'korea',
      },
    ],
  },
  {
    label: '标签',
    name: 'tags',
    options: [
      { label: '全部', value: '' },
      { label: '热血', value: 'rexue' },
      { label: '冒险', value: 'maoxian' },
      { label: '魔幻', value: 'mohuan' },
      { label: '神鬼', value: 'shengui' },
      { label: '搞笑', value: 'gaoxiao' },
      { label: '萌系', value: 'mengxi' },
      { label: '爱情', value: 'aiqing' },
      { label: '科幻', value: 'kehuan' },
      { label: '魔法', value: 'mofa' },
      { label: '格斗', value: 'gedou' },
      { label: '武侠', value: 'wuxia' },
      { label: '机战', value: 'jizhan' },
      { label: '战争', value: 'zhanzheng' },
      { label: '竞技', value: 'jingji' },
      { label: '体育', value: 'tiyu' },
      { label: '校园', value: 'xiaoyuan' },
      { label: '生活', value: 'shenghuo' },
      { label: '励志', value: 'lizhi' },
      { label: '历史', value: 'lishi' },
      { label: '伪娘', value: 'weiniang' },
      { label: '宅男', value: 'zhainan' },
      { label: '腐女', value: 'funv' },
      { label: '耽美', value: 'danmei' },
      { label: '百合', value: 'baihe' },
      { label: '后宫', value: 'hougong' },
      { label: '治愈', value: 'zhiyu' },
      { label: '美食', value: 'meishi' },
      { label: '推理', value: 'tuili' },
      { label: '悬疑', value: 'xuanyi' },
      { label: '恐怖', value: 'kongbu' },
      { label: '四格', value: 'sige' },
      { label: '职场', value: 'zhichang' },
      { label: '侦探', value: 'zhentan' },
      { label: '社会', value: 'shehui' },
      { label: '音乐', value: 'yinyue' },
      { label: '舞蹈', value: 'wudao' },
      { label: '杂志', value: 'zazhi' },
      { label: '黑道', value: 'heidao' },
    ],
  },
  {
    label: '受众',
    name: 'audience',
    options: [
      { label: '全部', value: '' },
      { label: '少女', value: 'shaonv' },
      { label: '少年', value: 'shaonian' },
      { label: '青年', value: 'qingnian' },
      { label: '儿童', value: 'ertong' },
      { label: '通用', value: 'tongyong' },
    ],
  },
  {
    label: '年份',
    name: 'year',
    options: [
      { label: '全部', value: '' },
      { label: '2021年', value: '2021' },
      { label: '2020年', value: '2020' },
      { label: '2019年', value: '2019' },
      { label: '2018年', value: '2018' },
      { label: '2017年', value: '2017' },
      { label: '2016年', value: '2016' },
      { label: '2015年', value: '2015' },
      { label: '2014年', value: '2014' },
      { label: '2013年', value: '2013' },
      { label: '2012年', value: '2012' },
      { label: '2011年', value: '2011' },
      { label: '2010年', value: '2010' },
      { label: '00年代', value: '200x' },
      { label: '90年代', value: '199x' },
      { label: '80年代', value: '198x' },
      { label: '更早', value: '197x' },
    ],
  },
  {
    label: '字母',
    name: 'letter',
    options: [
      { label: '全部', value: '' },
      { label: 'A', value: 'a' },
      { label: 'B', value: 'b' },
      { label: 'C', value: 'c' },
      { label: 'D', value: 'd' },
      { label: 'E', value: 'e' },
      { label: 'F', value: 'f' },
      { label: 'G', value: 'g' },
      { label: 'H', value: 'h' },
      { label: 'I', value: 'i' },
      { label: 'J', value: 'j' },
      { label: 'K', value: 'k' },
      { label: 'L', value: 'l' },
      { label: 'M', value: 'm' },
      { label: 'N', value: 'n' },
      { label: 'O', value: 'o' },
      { label: 'P', value: 'p' },
      { label: 'Q', value: 'q' },
      { label: 'R', value: 'r' },
      { label: 'S', value: 's' },
      { label: 'T', value: 't' },
      { label: 'U', value: 'u' },
      { label: 'V', value: 'v' },
      { label: 'W', value: 'w' },
      { label: 'X', value: 'x' },
      { label: 'Y', value: 'y' },
      { label: 'Z', value: 'z' },
      { label: '0-9', value: '0-9' },
    ],
  },
  {
    label: '状态',
    name: 'status',
    options: [
      { label: '全部', value: '' },
      { label: '连载', value: 'lianzai' },
      { label: '完结', value: 'wanjie' },
    ],
  },
  {
    label: '排序',
    name: 'sort',
    options: [
      { label: '最新发布', value: 'index.html' },
      { label: '最新更新', value: 'update.html' },
      { label: '人气最旺', value: 'view.html' },
      { label: '评分最高', value: 'rate.html' },
    ],
  },
];
export { FromInfo };
